(defpackage #:org.shirakumo.fraf.glfw.cffi
  (:use #:cl)
  (:shadow #:error #:char)
  (:export
   #:libglfw
   #:libglfw-wayland
   #:key-state
   #:hat-state
   #:mouse-button
   #:key
   #:modifier
   #:gamepad-button
   #:gamepad-axis
   #:error
   #:flag
   #:joystick-event
   #:monitor-event
   #:cursor
   #:video-mode
   #:video-mode-width
   #:video-mode-height
   #:video-mode-red-bits
   #:video-mode-green-bits
   #:video-mode-blue-bits
   #:video-mode-refresh-rate
   #:gamma-ramp
   #:gamma-ramp-red
   #:gamma-ramp-green
   #:gamma-ramp-blue
   #:gamma-ramp-size
   #:image
   #:image-width
   #:image-height
   #:image-pixels
   #:gamepad-state
   #:gamepad-state-buttons
   #:gamepad-state-axes
   #:allocator
   #:allocator-allocate
   #:allocator-reallocate
   #:allocator-deallocate
   #:allocator-user
   #:resolve-window
   #:error
   #:monitor-connected
   #:monitor-disconnected
   #:monitor
   #:joystick-connected
   #:joystick-disconnected
   #:joystick
   #:allocate
   #:reallocate
   #:deallocate
   #:window-position
   #:window-size
   #:window-close
   #:window-refresh
   #:window-focus
   #:window-iconify
   #:window-maximize
   #:framebuffer-size
   #:window-content-scale
   #:mouse-button
   #:mouse-position
   #:mouse-enter
   #:mouse-scroll
   #:key
   #:char
   #:char-modifiers
   #:drop
   #:init
   #:terminate
   #:init-hint
   #:init-allocator
   #:init-vulkan-loader
   #:get-version
   #:get-version-string
   #:get-error
   #:get-platform
   #:platform-supported
   #:get-monitors
   #:get-primary-monitor
   #:get-monitor-pos
   #:get-monitor-workarea
   #:get-monitor-physical-size
   #:get-monitor-content-scale
   #:get-monitor-name
   #:set-monitor-user-pointer
   #:get-monitor-user-pointer
   #:get-video-modes
   #:get-video-mode
   #:set-gamma
   #:get-gamma-ramp
   #:set-gamma-ramp
   #:default-window-hints
   #:window-hint
   #:window-hint-string
   #:create-window
   #:destroy-window
   #:window-should-close
   #:set-window-should-close
   #:set-window-title
   #:set-window-icon
   #:set-window-pos
   #:get-window-pos
   #:get-window-size
   #:set-window-size-limits
   #:set-window-aspect-ratio
   #:set-window-size
   #:get-framebuffer-size
   #:get-window-frame-size
   #:get-window-content-scale
   #:get-window-opacity
   #:set-window-opacity
   #:iconify-window
   #:restore-window
   #:maximize-window
   #:show-window
   #:hide-window
   #:focus-window
   #:request-window-attention
   #:get-window-monitor
   #:set-window-monitor
   #:get-window-attrib
   #:set-window-attrib
   #:get-window-user-pointer
   #:set-window-user-pointer
   #:poll-events
   #:wait-events
   #:wait-events-timeout
   #:post-empty-event
   #:get-input-mode
   #:set-input-mode
   #:raw-mouse-motion-supported
   #:get-key-name
   #:get-key-scancode
   #:get-key
   #:get-mouse-button
   #:get-cursor-pos
   #:set-cursor-pos
   #:create-cursor
   #:create-standard-cursor
   #:destroy-cursor
   #:set-cursor
   #:joystick-present
   #:get-joystick-axes
   #:get-joystick-buttons
   #:get-joystick-hats
   #:get-joystick-name
   #:get-joystick-guid
   #:set-joystick-user-pointer
   #:get-joystick-user-pointer
   #:joystick-is-gamepad
   #:update-gamepad-mappings
   #:get-gamepad-name
   #:get-gamepad-state
   #:set-clipboard-string
   #:get-clipboard-string
   #:get-time
   #:set-time
   #:get-timer-value
   #:get-timer-frequency
   #:make-context-current
   #:get-current-context
   #:swap-buffers
   #:swap-interval
   #:extension-supported
   #:get-proc-address
   #:vulkan-supported
   #:get-required-instance-extensions
   #:get-instance-proc-address
   #:get-physical-device-presentation-support
   #:create-window-surface
   #:set-error-callback
   #:set-monitor-callback
   #:set-winow-pos-callback
   #:set-window-size-callback
   #:set-window-close-callback
   #:set-window-refresh-callback
   #:set-window-focus-callback
   #:set-window-iconify-callback
   #:set-window-maximize-callback
   #:set-framebuffer-size-callback
   #:set-window-content-scale-callback
   #:set-key-callback
   #:set-char-callback
   #:set-char-mods-callback
   #:set-mouse-button-callback
   #:set-cursor-pos-callback
   #:set-cursor-enter-callback
   #:set-scroll-callback
   #:set-drop-callback
   #:set-joystick-callback
   #:get-win32-adapter
   #:get-win32-monitor
   #:get-win32-window
   #:get-wglcontext
   #:get-cocoa-monitor
   #:get-cocoa-window
   #:get-nsglcontext
   #:get-x11-display
   #:get-x11-adapter
   #:get-x11-monitor
   #:get-x11-window
   #:set-x11-selection-string
   #:get-x11-selection-string
   #:get-glxcontext
   #:get-glxwindow
   #:get-wayland-display
   #:get-wayland-monitor
   #:get-wayland-window
   #:get-egldisplay
   #:get-eglcontext
   #:get-eglsurface
   #:get-osmesa-color-buffer
   #:get-osmesa-depth-buffer
   #:get-osmesa-context))

(defpackage #:org.shirakumo.fraf.glfw
  (:use #:cl)
  (:local-nicknames
   (#:glfw #:org.shirakumo.fraf.glfw.cffi))
  (:shadow #:time #:char)
  (:import-from
   #:org.shirakumo.fraf.glfw.cffi
   #:allocate
   #:reallocate
   #:deallocate
   #:window-size
   #:window-close
   #:window-position
   #:window-size
   #:window-refresh
   #:window-focus
   #:window-iconify
   #:window-maximize
   #:framebuffer-size
   #:window-content-scale
   #:mouse-button
   #:mouse-position
   #:mouse-enter
   #:mouse-scroll
   #:key
   #:char
   #:char-modifiers
   #:drop)
  (:export
   #:glfw-error
   #:operation
   #:code
   #:message
   #:init
   #:shutdown
   #:foreign-object
   #:pointer
   #:destroy
   #:cursor
   #:monitor
   #:video-modes
   #:list-monitors
   #:primary-monitor
   #:location
   #:work-area
   #:physical-size
   #:content-scale
   #:name
   #:video-mode
   #:gamma
   #:gamma-ramp
   #:window
   #:width
   #:height
   #:aspect-ratio
   #:size-limits
   #:swap-interval
   #:title
   #:cursor
   #:register-callbacks
   #:allocate
   #:reallocate
   #:deallocate
   #:window-size
   #:window-close
   #:window-position
   #:window-size
   #:window-refresh
   #:window-focus
   #:window-iconify
   #:window-maximize
   #:framebuffer-size
   #:window-content-scale
   #:mouse-button
   #:mouse-position
   #:mouse-enter
   #:mouse-scroll
   #:key
   #:char
   #:char-modifiers
   #:drop
   #:should-close-p
   #:location
   #:size
   #:framebuffer-size
   #:frame-size
   #:content-scale
   #:opacity
   #:iconify
   #:restore
   #:maximize
   #:show
   #:hide
   #:focus
   #:request-attention
   #:monitor
   #:attribute
   #:input-mode
   #:poll-events
   #:key-state
   #:mouse-button-state
   #:cursor-location
   #:clipboard-string
   #:version
   #:platform
   #:time
   #:timestamp
   #:timestamp-resolution
   #:make-current
   #:get-current
   #:swap-buffers
   #:swap-interval
   #:cursor))
